export const TABLES = {
  specialties: {
    title: 'Специальности',
    hint: 'Направления подготовки и факультеты',
    icon: 'SP',
    key: 'SpecialtyID',
    fields: [
      { name: 'SpecialtyCode', label: 'Код специальности', type: 'text', required: true },
      { name: 'SpecialtyName', label: 'Название', type: 'text', required: true },
      { name: 'Faculty', label: 'Факультет', type: 'text', required: true },
    ],
    columns: ['SpecialtyID', 'SpecialtyCode', 'SpecialtyName', 'Faculty'],
    columnLabels: {
      SpecialtyID: 'ID',
      SpecialtyCode: 'Код',
      SpecialtyName: 'Название',
      Faculty: 'Факультет',
    },
  },
  groups: {
    title: 'Группы',
    hint: 'Учебные группы и связь со специальностями',
    icon: 'GR',
    key: 'GroupID',
    fields: [
      { name: 'GroupName', label: 'Название группы', type: 'text', required: true },
      { name: 'SpecialtyID', label: 'Специальность', type: 'select', lookup: 'specialties', required: true },
      { name: 'Course', label: 'Курс', type: 'number', required: true, min: 1, max: 6 },
    ],
    columns: ['GroupID', 'GroupName', 'SpecialtyDisplay', 'Course'],
    columnLabels: {
      GroupID: 'ID',
      GroupName: 'Группа',
      SpecialtyDisplay: 'Специальность',
      Course: 'Курс',
    },
  },
  students: {
    title: 'Студенты',
    hint: 'Карточки студентов и принадлежность к группам',
    icon: 'ST',
    key: 'StudentID',
    fields: [
      { name: 'LastName', label: 'Фамилия', type: 'text', required: true },
      { name: 'FirstName', label: 'Имя', type: 'text', required: true },
      { name: 'MiddleName', label: 'Отчество', type: 'text' },
      { name: 'GroupID', label: 'Группа', type: 'select', lookup: 'groups', required: true },
      { name: 'Phone', label: 'Телефон', type: 'text' },
      { name: 'Address', label: 'Адрес', type: 'text' },
      { name: 'Email', label: 'Эл. почта', type: 'email' },
      { name: 'BirthDate', label: 'Дата рождения', type: 'date' },
    ],
    columns: ['StudentID', 'LastName', 'FirstName', 'MiddleName', 'GroupName', 'BirthDate', 'Email'],
    columnLabels: {
      StudentID: 'ID',
      LastName: 'Фамилия',
      FirstName: 'Имя',
      MiddleName: 'Отчество',
      GroupName: 'Группа',
      BirthDate: 'Дата рождения',
      Email: 'Почта',
    },
  },
  teachers: {
    title: 'Преподаватели',
    hint: 'Справочник преподавателей, должностей и контактов',
    icon: 'TC',
    key: 'TeacherID',
    fields: [
      { name: 'LastName', label: 'Фамилия', type: 'text', required: true },
      { name: 'FirstName', label: 'Имя', type: 'text', required: true },
      { name: 'MiddleName', label: 'Отчество', type: 'text' },
      { name: 'AcademicDegree', label: 'Ученая степень', type: 'text' },
      { name: 'AcademicTitle', label: 'Ученое звание', type: 'text' },
      { name: 'Position', label: 'Должность', type: 'text' },
      { name: 'Phone', label: 'Телефон', type: 'text' },
      { name: 'Address', label: 'Адрес', type: 'text' },
      { name: 'Email', label: 'Эл. почта', type: 'email' },
    ],
    columns: ['TeacherID', 'LastName', 'FirstName', 'MiddleName', 'AcademicDegree', 'AcademicTitle', 'Position', 'Email'],
    columnLabels: {
      TeacherID: 'ID',
      LastName: 'Фамилия',
      FirstName: 'Имя',
      MiddleName: 'Отчество',
      AcademicDegree: 'Степень',
      AcademicTitle: 'Звание',
      Position: 'Должность',
      Email: 'Почта',
    },
  },
  subjects: {
    title: 'Предметы',
    hint: 'Дисциплины, семестры, часы и форма контроля',
    icon: 'SB',
    key: 'SubjectID',
    fields: [
      { name: 'SubjectName', label: 'Название', type: 'text', required: true },
      { name: 'Semester', label: 'Семестр', type: 'number', required: true, min: 1, max: 12 },
      { name: 'HoursCount', label: 'Количество часов', type: 'number', required: true, min: 0 },
      { name: 'ControlForm', label: 'Форма контроля', type: 'text', required: true },
    ],
    columns: ['SubjectID', 'SubjectName', 'Semester', 'HoursCount', 'ControlForm'],
    columnLabels: {
      SubjectID: 'ID',
      SubjectName: 'Название',
      Semester: 'Семестр',
      HoursCount: 'Часы',
      ControlForm: 'Контроль',
    },
  },
  auditories: {
    title: 'Аудитории',
    hint: 'Справочник учебных помещений',
    icon: 'RM',
    key: 'AuditoryID',
    fields: [
      { name: 'RoomNumber', label: 'Номер', type: 'text', required: true },
      { name: 'RoomType', label: 'Тип аудитории', type: 'text', required: true },
    ],
    columns: ['AuditoryID', 'RoomNumber', 'RoomType'],
    columnLabels: {
      AuditoryID: 'ID',
      RoomNumber: 'Номер',
      RoomType: 'Тип',
    },
  },
  discipline: {
    title: 'Учебная нагрузка',
    hint: 'Связка предмета, преподавателя, группы и часов',
    icon: 'DS',
    key: 'DisciplineID',
    fields: [
      { name: 'SubjectID', label: 'Предмет', type: 'select', lookup: 'subjects', required: true },
      { name: 'TeacherID', label: 'Преподаватель', type: 'select', lookup: 'teachers', required: true },
      { name: 'GroupID', label: 'Группа', type: 'select', lookup: 'groups', required: true },
      { name: 'LectureHours', label: 'Лекции', type: 'number', required: true, min: 0 },
      { name: 'PracticalHours', label: 'Практика', type: 'number', required: true, min: 0 },
      { name: 'LaboratoryHours', label: 'Лабораторные', type: 'number', required: true, min: 0 },
      { name: 'OtherWorkHours', label: 'Другая работа', type: 'number', required: true, min: 0 },
      { name: 'ControlHours', label: 'Контрольные часы', type: 'number', step: '0.01', min: 0 },
    ],
    columns: [
      'DisciplineID',
      'SubjectName',
      'TeacherName',
      'GroupName',
      'LectureHours',
      'PracticalHours',
      'LaboratoryHours',
      'OtherWorkHours',
      'ControlForm',
      'CalculatedControlHours',
    ],
    columnLabels: {
      DisciplineID: 'ID',
      SubjectName: 'Предмет',
      TeacherName: 'Преподаватель',
      GroupName: 'Группа',
      LectureHours: 'Лекции',
      PracticalHours: 'Практика',
      LaboratoryHours: 'Лаб.',
      OtherWorkHours: 'Прочее',
      ControlForm: 'Контроль',
      CalculatedControlHours: 'Контр. часы',
    },
  },
};

export const TABLE_KEYS = Object.keys(TABLES);
